added config.json path #115
vinitshahdeo/PortScanner pull request #116
Opened 2021-01-29 19:00 UTC by Vinamrata1086

# Description

Added the path of ```config.json``` to src/single/scanner.py for python3.8

Fixes # 115

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added all the three reviewers: @vinitshahdeo, @kashish121 & @ishika1727

2021-01-30 15:46 UTC, vinitshahdeo reviewed
@Kashish121 Have a look into this.

2021-01-30 16:16 UTC, Kashish121 commented
Also, add a screenshot of the working code. :)

2021-01-30 16:21 UTC, Kashish121 requested changes

2021-01-30 16:21 UTC, Kashish121 commented on src/single/scanner.py
> +print('Scanning Completed in: ', total)
Linting issue.

2021-01-30 16:21 UTC, Kashish121 commented on src/single/scanner.py
> +total = t2 - t1
Linting issue.

2021-01-30 16:21 UTC, Kashish121 commented on src/single/scanner.py
> +    print("Couldn't connect to server")
Linting issue.

2021-01-30 16:21 UTC, Kashish121 commented on src/single/scanner.py
> +    print("Hostname could not be resolved. Exiting")
Linting issue. 
`print ("...")` instead of `print("...")`

2021-01-30 16:21 UTC, Kashish121 commented on src/single/scanner.py
> +    for port in range(loRange, hiRange):
Linting issue. It should be `range(loRange,hiRange):` and not `range(loRange, hiRange): `.
Follow the format of code previously used.

2021-01-30 16:21 UTC, Kashish121 commented on src/single/scanner.py
No need for more than 1 extra new line.

2021-01-30 16:21 UTC, Kashish121 commented on src/single/scanner.py
> +
No need for more than 1 extra new line.

2021-01-30 16:21 UTC, Kashish121 commented on src/single/scanner.py
> +
No need for more than 1 extra new line, Please remove line 15 or 16.

2021-01-31 11:20 UTC, Vinamrata1086 commented on src/single/scanner.py
> +
done

2021-02-01 05:34 UTC, Kashish121 approved these changes
@Vinamrata1086 the code looks just fine. 💯 Please add the required screenshots and this PR will be good to go.

2021-02-01 10:28 UTC, Vinamrata1086 commented
> @Vinamrata1086 the code looks just fine. 💯 Please add the required screenshots and this PR will be good to go.

I have added the required screenshot [above](https://github.com/vinitshahdeo/PortScanner/pull/116#issue-564173564) with the whole code.

2021-02-02 08:51 UTC, merged